#!/usr/bin/env python3
"""Generates docs/diagram-index.md: a table of every src/**/*.drawio diagram
with an SVG preview and a draw.io edit link, under headings mirroring src/'s
subfolder structure (capped at 3 levels deep) with a linkable TOC.

This file is fully auto-generated -- do not hand-edit docs/diagram-index.md,
re-run this script instead.
"""
import argparse
import os
import re
import subprocess
from pathlib import Path
from urllib.parse import quote

MAX_HEADING_LEVELS = 3


def git_remote_slug(default):
    try:
        url = subprocess.run(
            ["git", "config", "--get", "remote.origin.url"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return default
    m = re.search(r"[:/]([^/:]+/[^/]+?)(\.git)?$", url)
    return m.group(1) if m else default


def github_slug(text, seen):
    slug = text.strip().lower()
    slug = re.sub(r"[^\w\- ]", "", slug)
    slug = slug.replace(" ", "-")
    base = slug
    n = 0
    while slug in seen:
        n += 1
        slug = f"{base}-{n}"
    seen.add(slug)
    return slug


def collect_diagrams(src_dir):
    diagrams = []
    for path in sorted(src_dir.rglob("*.drawio")):
        rel = path.relative_to(src_dir)
        diagrams.append(rel)
    return diagrams


def group_by_heading(diagrams):
    """Groups diagrams by their heading path, capped at MAX_HEADING_LEVELS.

    Returns an ordered dict-like list of (heading_path_tuple, [ (display_name, rel_path), ... ]).
    heading_path_tuple has length 0..MAX_HEADING_LEVELS. Anything beyond that
    depth is collapsed into the deepest heading, with the remaining path
    segments prefixed onto the displayed diagram name.
    """
    groups = {}
    order = []
    for rel in diagrams:
        parts = rel.parts[:-1]  # directory components only
        heading_path = tuple(parts[:MAX_HEADING_LEVELS])
        leftover = parts[MAX_HEADING_LEVELS:]
        stem = rel.stem
        display_name = "/".join((*leftover, stem)) if leftover else stem
        if heading_path not in groups:
            groups[heading_path] = []
            order.append(heading_path)
        groups[heading_path].append((display_name, rel))
    return [(hp, groups[hp]) for hp in order]


def make_edit_link(repo, branch, src_rel):
    path = f"{repo}/{branch}/{src_rel.as_posix()}"
    encoded = quote(path, safe="")
    return f"https://app.diagrams.net/#H{encoded}"


def render(diagrams, repo, branch, images_dir_name):
    groups = group_by_heading(diagrams)
    seen_slugs = set()
    toc_lines = []
    body_lines = []

    for heading_path, entries in groups:
        for depth, segment in enumerate(heading_path, start=1):
            level = 1 + depth
            slug = github_slug(segment, seen_slugs)
            indent = "  " * (depth - 1)
            toc_lines.append(f"{indent}- [{segment}](#{slug})")
            body_lines.append(f"\n{'#' * level} {segment}\n")

        body_lines.append("")
        body_lines.append("| Diagram | Preview | Edit |")
        body_lines.append("|---|---|---|")
        for display_name, rel in sorted(entries):
            src_rel = Path("src") / rel
            image_rel = Path(images_dir_name) / rel.with_suffix(".svg")
            edit_link = make_edit_link(repo, branch, src_rel)
            body_lines.append(
                f"| {display_name} | ![{display_name}](../{image_rel.as_posix()}) "
                f"| [Open in draw.io]({edit_link}) |"
            )

    return toc_lines, body_lines


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src", default="src", help="source directory of .drawio files")
    parser.add_argument("--images", default="auto-images", help="rendered SVG directory")
    parser.add_argument("--out", default="docs/diagram-index.md", help="output markdown file")
    parser.add_argument("--repo", default=None, help="owner/repo, e.g. wesketchum/dunedaq-diagrams")
    parser.add_argument("--branch", default="main", help="branch used in draw.io edit links")
    args = parser.parse_args()

    repo_root = Path(
        subprocess.run(
            ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True,
        ).stdout.strip()
    )
    os.chdir(repo_root)

    repo = args.repo or git_remote_slug("wesketchum/dunedaq-diagrams")
    src_dir = Path(args.src)
    diagrams = collect_diagrams(src_dir)
    toc_lines, body_lines = render(diagrams, repo, args.branch, args.images)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Diagram index",
        "",
        "Auto-generated by `scripts/generate-index.py` -- do not hand-edit,",
        "re-run the script instead.",
        "",
    ]
    if toc_lines:
        lines.extend(toc_lines)
    lines.extend(body_lines)
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path} ({len(diagrams)} diagram(s))")


if __name__ == "__main__":
    main()
